package com.namma.santhe.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.util.Locale

object PdfUtils {

    fun generateAndSharePdf(
        context: Context,
        title: String,
        dateString: String,
        sales: Double,
        collected: Double,
        pending: Double
    ) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
        val page = document.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val paint = Paint()

        // Draw Title
        paint.color = Color.rgb(242, 110, 34) // Orange color
        paint.textSize = 32f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textAlign = Paint.Align.CENTER
        canvas.drawText("Namma-Santhe Ledger", 595f / 2, 80f, paint)

        // Draw Subtitle / Date
        paint.color = Color.BLACK
        paint.textSize = 24f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText(title, 595f / 2, 130f, paint)
        paint.textSize = 18f
        paint.color = Color.DKGRAY
        canvas.drawText(dateString, 595f / 2, 160f, paint)

        // Draw Content
        paint.textAlign = Paint.Align.LEFT
        paint.textSize = 22f
        paint.color = Color.BLACK
        val startY = 250f
        val lineSpacing = 50f
        val startX = 100f

        val salesText = String.format(Locale.getDefault(), "Total Sales (ಮಾರಾಟ): ₹%.2f", sales)
        val collectedText = String.format(Locale.getDefault(), "Total Collected (ಸ್ವೀಕರಿಸಿದ): ₹%.2f", collected)
        val pendingText = String.format(Locale.getDefault(), "Total Pending (ಬಾಕಿ): ₹%.2f", pending)

        // Draw Sales
        paint.color = Color.rgb(76, 175, 80) // Green
        canvas.drawText(salesText, startX, startY, paint)

        // Draw Collected
        paint.color = Color.rgb(33, 150, 243) // Blue
        canvas.drawText(collectedText, startX, startY + lineSpacing, paint)

        // Draw Pending
        paint.color = Color.rgb(244, 67, 54) // Red
        canvas.drawText(pendingText, startX, startY + (lineSpacing * 2), paint)

        // Footer
        paint.textAlign = Paint.Align.CENTER
        paint.color = Color.GRAY
        paint.textSize = 14f
        canvas.drawText("Generated by Namma-Santhe Ledger App", 595f / 2, 800f, paint)

        document.finishPage(page)

        // Save PDF to cache dir
        val pdfsDir = File(context.cacheDir, "pdfs")
        if (!pdfsDir.exists()) {
            pdfsDir.mkdirs()
        }
        val pdfFile = File(pdfsDir, "Namma_Santhe_Summary.pdf")
        
        try {
            val fos = FileOutputStream(pdfFile)
            document.writeTo(fos)
            document.close()
            fos.close()
            
            sharePdf(context, pdfFile)
        } catch (e: Exception) {
            e.printStackTrace()
            document.close()
        }
    }

    private fun sharePdf(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            context.applicationContext.packageName + ".fileprovider",
            file
        )

        val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(android.content.Intent.EXTRA_STREAM, uri)
            putExtra(android.content.Intent.EXTRA_SUBJECT, "Namma Santhe Summary")
            putExtra(android.content.Intent.EXTRA_TEXT, "Here is the summary report from Namma-Santhe Ledger.")
            addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        context.startActivity(android.content.Intent.createChooser(intent, "Share PDF Summary"))
    }
}
